version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      APP_ENV: local
    depends_on:
      - pg
      - redis
    networks: [appnet]

  web:
    image: nginx:1.27-alpine
    container_name: laravel-nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html:ro
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks: [appnet]

  pg:
    image: postgres:16-alpine
    container_name: pg
    environment:
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/init:/docker-entrypoint-initdb.d:ro
    ports:
      - "5435:5432"
    networks: [appnet]

  redis:
    image: redis:7-alpine
    container_name: redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks: [appnet]

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-queue
    working_dir: /var/www/html
    depends_on:
      - app
      - redis
      - pg
    volumes:
      - ./:/var/www/html
    command: sh -lc "php artisan queue:work --tries=3 --sleep=1"
    networks: [appnet]

volumes:
  pgdata:
  redisdata:

networks:
  appnet:
    driver: bridge
